### ISSUE TITLE
Raspberry pi specific instructions for Docker

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/coral-pi-rest-server#28]
As per https://github.com/robmarkcole/coral-pi-rest-server/issues/13 you cant currently use the coral with system-wide python in Buster, so the recommended solution is Docker on the pi. @lmamakos can we have a single docker image that will work on Ubuntu & Raspbian? If not will we require hardware specific instructions on building the container?

**Comment by lmamakos** [comment]
I believe that you'd need a different pre-built container because of the different CPU architecture.  I don't know if you'd need a different Dockerfile; it might need to be slightly more clever to install the right google libraries for Raspian, though maybe their installation script does that already.

I know only enough about Docker to be a danger to myself and others, so I'm certainly happy to have someone with more familiarity chime in with some best-practice advice here on how to do cross platform container builds.

**Comment by robmarkcole** [comment]
OK for raspberry we should instruct people to install the disk images from https://github.com/google-coral/edgetpu-platforms#prebuilt-images-for-raspberry-pis 
These have a consistent file structure and all dependencies installed. We keep docker for linux desktops only IMO

**Comment by robmarkcole** [comment]
Review down the line if docker is required for RPI
